export const BuildingQuote = [
  {
    type: "residential",
    name: "Standard Bungalow",
    region: "nairobi",
    price: "41600 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Middle-Class Maisonette",
    region: "nairobi",
    price: "46800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Bungalow",
    region: "nairobi",
    price: "55000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Maisonette",
    region: "nairobi",
    price: " 72000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard Low-Rise Office Block",
    region: "nairobi",
    price: "54100 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard High-Rise Office Block",
    region: "nairobi",
    price: "70350  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Luxurious High-Rise Office Block",
    region: "nairobi",
    price: "100800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Small Scale Shopping Centre",
    region: "nairobi",
    price: "44500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Standard Urban Shopping Complex ",
    region: "nairobi",
    price: "57000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "All-Inclusive Shopping Mall",
    region: "nairobi",
    price: "65500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Double Storey Factory",
    region: "nairobi",
    price: "44000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "High Tech Factory/Lab",
    region: "nairobi",
    price: "81700 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Warehouse ",
    region: "nairobi",
    price: "40500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Cold Storage Centre",
    region: "nairobi",
    price: "41100 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Administration Office",
    region: "nairobi",
    price: "42000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard Bungalow",
    region: "nairobi",
    price: "41600 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Middle-Class Maisonette",
    region: "nairobi",
    price: "46800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Bungalow",
    region: "nairobi",
    price: "55000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Maisonette",
    region: "nairobi",
    price: " 72000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard Low-Rise Office Block",
    region: "nairobi",
    price: "54100 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard High-Rise Office Block",
    region: "nairobi",
    price: "70350  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Luxurious High-Rise Office Block",
    region: "nairobi",
    price: "100800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Small Scale Shopping Centre",
    region: "nairobi",
    price: "44500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Standard Urban Shopping Complex ",
    region: "nairobi",
    price: "57000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "All-Inclusive Shopping Mall",
    region: "nairobi",
    price: "65500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Double Storey Factory",
    region: "nairobi",
    price: "44000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "High Tech Factory/Lab",
    region: "nairobi",
    price: "81700 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Warehouse ",
    region: "nairobi",
    price: "40500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Cold Storage Centre",
    region: "nairobi",
    price: "41100 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Administration Office",
    region: "nairobi",
    price: "42000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard Bungalow",
    region: "coast",
    price: "43250 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Middle-Class Maisonette",
    region: "coast",
    price: "50000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Bungalow",
    region: "coast",
    price: "58400  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Maisonette",
    region: "coast",
    price: " 65750  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard Low-Rise Apartment Block",
    region: "coast",
    price: "42500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard High-Rise Apartment Block",
    region: "coast",
    price: "50500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Apartment Block",
    region: "coast",
    price: " 65000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard Low-Rise Office Block",
    region: "coast",
    price: "58700 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard High-Rise Office Block",
    region: "coast",
    price: "75000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Luxurious High-Rise Office Block",
    region: "coast",
    price: "97450 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Business Park",
    region: "coast",
    price: "64500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Small Scale Shopping Centre",
    region: "coast",
    price: "46250 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Standard Urban Shopping Complex ",
    region: "coast",
    price: "60000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "All-Inclusive Shopping Mall",
    region: "coast",
    price: "71350 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Double Storey Factory",
    region: "coast",
    price: "43500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "High Tech Factory/Lab",
    region: "coast",
    price: "82250 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Warehouse ",
    region: "coast",
    price: "36000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Cold Storage Centre",
    region: "coast",
    price: "44800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Administration Office",
    region: "coast",
    price: "43100 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard Bungalow",
    region: "western",
    price: "42000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Middle-Class Maisonette",
    region: "western",
    price: "51750 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Bungalow",
    region: "western",
    price: "65400  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Maisonette",
    region: "western",
    price: " 74000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard Low-Rise Apartment Block",
    region: "western",
    price: "49800 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Standard High-Rise Apartment Block",
    region: "western",
    price: "54650 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "residential",
    name: "Luxurious Apartment Block",
    region: "western",
    price: " 63000  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard Low-Rise Office Block",
    region: "western",
    price: "58000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Standard High-Rise Office Block",
    region: "western",
    price: "80150  ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "commercial",
    name: "Luxurious High-Rise Office Block",
    region: "western",
    price: "95000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Business Park",
    region: "western",
    price: "67700 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Small Scale Shopping Centre",
    region: "western",
    price: "48500 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "Standard Urban Shopping Complex ",
    region: "western",
    price: "60000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "business",
    name: "All-Inclusive Shopping Mall",
    region: "western",
    price: "72000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Double Storey Factory",
    region: "western",
    price: "46200 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "High Tech Factory/Lab",
    region: "western",
    price: "83000 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Warehouse ",
    region: "western",
    price: "46900 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Cold Storage Centre",
    region: "western",
    price: "45050 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
  {
    type: "industrial",
    name: "Administration Office",
    region: "western",
    price: "44300 ",
    desc: "Key features of the building: Example: #of floors/# of rooms",
  },
];
